name: Digital Marketing
favicon: null
layout_spectrum: 0.03046794910915196
typography_spectrum: 0.6073169060982764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4766498759854585
  lightness: 0.7900182988960296
  saturation: 0.9590353700332344
  rhythmicContrast: 0.5782187911681831
purpose: []
